"""criacao inicial

Revision ID: 3294ca72bb97
Revises: 
Create Date: 2025-08-16 12:04:45.654053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3294ca72bb97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('matricula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Atividade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('materia', sa.String(length=255), nullable=False),
    sa.Column('assunto', sa.Text(), nullable=False),
    sa.Column('data_hora_realizacao', sa.DateTime(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('tipo_atividade', sa.Enum('Prova_Objetiva', 'Prova_Discursiva', 'Prova_Mista', 'Seminario', 'Lista_de_Atividades', name='tipoatividade'), nullable=False),
    sa.Column('data_hora_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('forma_aplicacao', sa.Enum('Individual', 'Em_Dupla', 'Em_Grupo', name='formaaplicacao'), nullable=False),
    sa.Column('links_material', sa.Text(), nullable=True),
    sa.Column('permite_consulta', sa.Boolean(), nullable=False),
    sa.Column('pontuacao', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('local_prova', sa.Enum('Sala_de_Aula', 'Laboratorio', 'AVA', 'Ginasio', name='localprova'), nullable=False),
    sa.Column('materiais_necessarios', sa.Text(), nullable=True),
    sa.Column('outros_materiais', sa.Text(), nullable=True),
    sa.Column('avaliativa', sa.Boolean(), nullable=False),
    sa.Column('turma', sa.Enum('Informatica_1A', 'Informatica_1B', 'Informatica_1C', 'Informatica_2A', 'Informatica_2B', 'Informatica_2C', 'Informatica_3A', 'Informatica_3B', 'Informatica_3C', 'Edificacoes_1A', 'Edificacoes_1B', 'Edificacoes_2A', 'Edificacoes_2B', 'Edificacoes_3A', name='turma'), nullable=False),
    sa.ForeignKeyConstraint(['matricula'], ['Usuario.matricula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ParticipacaoEvento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=20), nullable=False),
    sa.Column('papel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['Evento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.matricula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PostForum',
    sa.Column('id_post', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_post', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula'], ['Usuario.matricula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_post')
    )
    op.create_table('ProgramacaoEvento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(), nullable=False),
    sa.Column('horario_fim', sa.DateTime(), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=False),
    sa.Column('organizador', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['Evento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reclamacao',
    sa.Column('id_reclamacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('topico', sa.Enum('Calendario', 'Cadastro_de_Perfil', 'Cadastro_de_Atividades', 'Avaliacoes', 'Outros', name='topicoreclamacao'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_reclamacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula'], ['Usuario.matricula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reclamacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reclamacao')
    op.drop_table('ProgramacaoEvento')
    op.drop_table('PostForum')
    op.drop_table('ParticipacaoEvento')
    op.drop_table('Atividade')
    op.drop_table('Usuario')
    op.drop_table('Evento')
    # ### end Alembic commands ###
